language: python

# run python versions
python:
  - "2.7"
  - "3.6"

sudo: required

# command to install dependencies
install:
  - pip install -U pytest
  - pip install unittest2
  - pip install coverage

# Command to run tests
script:
  - pytest
  - coverage run -m pytest test/test_core.py
  - coverage report -m
notification:
  email: false